function attachSolutionButtonListeners_question13(button) {
    button.addEventListener('click', function() {
        // Reset styles for dropdowns
        document.querySelectorAll('.dropdown-group select').forEach(select => {
            select.style.color = '';
        });

        // Check the answers
        const selectedOption1 = document.getElementById('answer13A').value;
        const selectedOption2 = document.getElementById('answer13B').value;
        const correctAnswer1 = 'All the domain controllers in the forest';
        const correctAnswer2 = 'The access key generated by the Microsoft Defender for Identity portal';
        let allCorrect = true;

        // Check if the selected answers are correct
        if (selectedOption1 !== correctAnswer1) {
            allCorrect = false;
            document.getElementById('answer13A').style.color = 'red';
        }
        if (selectedOption2 !== correctAnswer2) {
            allCorrect = false;
            document.getElementById('answer13B').style.color = 'red';
        }

        // Display solution info
        const solutionInfoElement = document.getElementById('solutionInfo_question13');
        if (solutionInfoElement) {
            if (allCorrect) {
                solutionInfoElement.classList.add('highlight'); // Apply yellow background if needed
                solutionInfoElement.classList.remove('incorrect');
                score++; // Increment the score if the answer is correct
            } else {
                solutionInfoElement.classList.add('incorrect');
                solutionInfoElement.classList.remove('highlight');
                const correctAnswersElement = document.getElementById('correctAnswers_question13');
                if (correctAnswersElement) {
                    correctAnswersElement.style.display = 'block';
                }
            }
            solutionInfoElement.style.display = 'block';
        }

        showFinalScore();
    });
}

document.addEventListener('DOMContentLoaded', function() {
    document.querySelectorAll('.solutionButton').forEach(button => {
        attachSolutionButtonListeners_question13(button);
    });
});

function showFinalScore() {
    const finalScoreElement = document.getElementById('finalScore');
    if (finalScoreElement) {
        const percentage = (score / totalQuestions) * 100;
        finalScoreElement.textContent = `Final Score: ${score}/${totalQuestions} (${percentage.toFixed(2)}%)`;
    }
}
